apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edgex-core-config-seed
  name: edgex-core-config-seed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: edgex-core-config-seed
    spec:
      containers:
      - image: edgexfoundry/docker-core-config-seed-go:0.7.1
        name: edgex-config-seed
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: data-db
        - mountPath: /edgex/logs
          name: edgex-logs
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      restartPolicy: Always
      volumes:
      - name: data-db
        hostPath:
          path: /data/db
      - name: edgex-logs
        hostPath:
          path: /edgex/logs
      - name: consul-config
        hostPath:
          path: /consul/config
      - name: consul-data
        hostPath:
          path: /consul/data
status: {}
