apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: edgex-export-distro
  name: edgex-export-distro
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: edgex-export-distro
    spec:
      containers:
      - image: akozyrev/edgex-export-distro:latest
        name: edgex-export-distro
        env:
        - name: EXPORT_CLIENT_DISTRO_HOST
          value: edgex-distro
        - name: EXPORT_DISTRO_DATA_HOST
          value: edgex-core-data
        - name: EXPORT_CLIENT_CONSUL_HOST
          value: edgex-config-seed
        - name: EXPORT_DISTRO_MQTTS_CERT_FILE
          value: none
        - name: EXPORT_DISTRO_MQTTS_KEY_FILE
          value: none
        ports:
        - containerPort: 48070
        - containerPort: 5566
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: data-db
        - mountPath: /edgex/logs
          name: edgex-logs
        - mountPath: /consul/config
          name: consul-config
        - mountPath: /consul/data
          name: consul-data
      restartPolicy: Always
      volumes:
      - name: data-db
        hostPath:
          path: /data/db
      - name: edgex-logs
        hostPath:
          path: /edgex/logs
      - name: consul-config
        hostPath:
          path: /consul/config
      - name: consul-data
        hostPath:
          path: /consul/data
status: {}
