apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-core-config-seed
  name: edgex-core-config-seed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: edgex-core-config-seed
status:
  loadBalancer: {}
