apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-device-virtual
  name: edgex-device-virtual
spec:
  ports:
  - name: "49900"
    port: 49900
    targetPort: 49900
  selector:
    io.kompose.service: edgex-device-virtual
status:
  loadBalancer: {}
