apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: edgex-files
  name: edgex-files
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    io.kompose.service: edgex-files
status:
  loadBalancer: {}
